Move `depends_on` under `help`

diff --git a/bin/journal b/bin/journal
--- a/bin/journal
+++ b/bin/journal
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+depends_on () {
+  command -v "$0" >/dev/null 2>&1 || {
+    echo "Dependency \"$0\" not found. Aborting." >&2;
+    exit 1;
+  }
+}
+
 help () {
   depends_on cat
 
@@ -11,13 +18,6 @@ help () {
   Options:
   -h --help         Show this screen
 END
-}
-
-depends_on () {
-  command -v "$0" >/dev/null 2>&1 || {
-    echo "Dependency \"$0\" not found. Aborting." >&2;
-    exit 1;
-  }
 }
 
 get_base_dir () {
